drop table if exists entries;
create table entries (
	id integer primary key autoincrement,
	movie text not null,
	source text not null,
	quote text unique not null,
	score integer not null,
	positive_nbo float,
	negative_nbo float,
	label_nbo text,
	positive_nbt float,
	negative_nbt float,
	label_nbt text,
	positive_nbth float,
	negative_nbth float,
	label_nbth text,
	positive_nbf float,
	negative_nbf float,
	label_nbf text,
	positive_nbfi float,
	negative_nbfi float,
	label_nbfi text,
	label_dto text,
	label_dtt text,
	label_dtth text
);
